templates:
  - posix:
    - unp.template
    - unp_make.template
    - unp_read.template
    - unp_write.template
    - unp_close.template
  - cancel: null

modules:
  - posix:
    - unp.h
    - unp_make.c
    - unp_read.c
    - unp_write.c
    - unp_close.c
